config:
  partial_parse: true
jaffle_shop:
  target: fabric-dev
  outputs:    
    fabric-dev:
      authentication: auto
      database: dbt_jaffle_shop
      driver: ODBC Driver 18 for SQL Server
      host: 3v4cy3mfd7fuzgxdzvpkdtfdme-f44zlkwse5yu5nfku6imlxta34.datawarehouse.pbidedicated.windows.net
      schema: dbt_test
      threads: 4
      type: fabric