config:
  partial_parse: true
jaffle_shop:
  target: fabric-dev
  outputs:    
    fabric-dev:
      authentication: ActiveDirectoryIntegrated
      database: jaffle_shop_warehouse
      driver: ODBC Driver 18 for SQL Server
      host: 3v4cy3mfd7fuzgxdzvpkdtfdme-cal2aw4dteputh7452dsyf5h2m.datawarehouse.pbidedicated.windows.net
      schema: fabric
      threads: 4
      type: fabric

    