config:
  partial_parse: true
jaffle_shop:
  target: fabric-dev
  outputs:    
    fabric-dev:
      authentication: auto
      database: jaffle_shop_warehouse
      driver: ODBC Driver 18 for SQL Server
      host: 3v4cy3mfd7fuzgxdzvpkdtfdme-ntjxya4umqzehojgo6rsy7iczq.datawarehouse.pbidedicated.windows.net
      schema: fabric
      threads: 4
      type: fabric